170930
shldhee/markupStudy pull request #1
Opened 2017-10-24 13:36 UTC by shldhee

create pull request

2017-10-24 14:19 UTC, JaesunPark requested changes
일부 수정 필요

2017-10-24 14:19 UTC, JaesunPark commented on css/reset.css
> +	line-height: 1;
`line-height`를 px로 작성하지 않을 경우

폰트 간격으로 인한 디자인 검수에 애로사항이 있을 수 있습니다.

기억해두었다가 나중에 이런 이슈가 있으면 참고해주시면 되겠습니다.

2017-10-24 14:19 UTC, JaesunPark commented on css/style.css
> +#wrap { box-sizing: border-box; width: 600px; margin: 0 auto; padding: 20px; }
`div#wrap`과 같이 전체를 감싸고 있는 요소에 `box-sizing` 속성을 주는것에 대해서는 신중하게 생각 후 속성을 적용하는것이 좋습니다.

2017-10-24 14:19 UTC, JaesunPark commented on css/style.css
> +.tit_text { font-size: 48px; font-weight: bold; }
`.tit_text`에 `line-height`가 1로 선언되어있어 `.tit_text`의 영역이 부모 `div.tit`를 벗어납니다.

`line-height`를 수정해야 할 것 같네요.

2017-10-24 14:19 UTC, JaesunPark commented on index.html
> +    <a class="content" href="#">
아래 평점 리스트에 링크가 들어가야 하므로 `a.content`의 마크업이 수정되어야 합니다.

2017-10-24 14:19 UTC, JaesunPark commented on index.html
> +      <h1 class="tit_text">평점&리뷰</h1>
`h1.tit_text`의 텍스트 "평점&리뷰"에 "&amp;"가 누락되었습니다.

2017-10-24 14:19 UTC, JaesunPark commented on css/style.css
> +.sub_tit { float: left; font-size: 24px; font-weight: bold; color: #00f;}
`line-height`가 1로 선언되어있어 `h2.sub_tit`가 부모인 `div.detail_top`의 영역을 벗어납니다.

2017-10-24 14:19 UTC, JaesunPark commented on css/style.css
> +.rank_star_wrap {position: relative; top:4px; right: 10px; float: left; width: 74px; height: 12px; }
`position` 속성은 절대값입니다.

`.rank_star_wrap`의 간격은 `position`값이 없이도 처리가 가능할 것으로 보입니다.

2017-10-24 14:19 UTC, JaesunPark commented on index.html
> +            <div class="rank_star_wrap">
`div. rank_star_wrap `의 자식 요소들에
텍스트가 제공되고있지 않습니다.

스크린리더기를 이용하는 사용자 입장에서는 평점에 대한 점수를 전혀 알 수 없습니다.

텍스트 제공이 필요합니다.

2017-10-24 14:19 UTC, JaesunPark commented on index.html
> +        <div class="detail_bottom">
`div.detail_bottom`의 안에 있는 텍스트들은
리스트로 마크업을 할 수 있다고 생각됩니다.

마크업 수정이 필요하다고 생각되네요.

2017-10-24 14:19 UTC, JaesunPark commented on index.html
> +  <title></title>
`title`에 아무런 텍스트가 제공되고있지 않습니다.

텍스트를 추가해주셔야 할 것 같습니다.

2017-10-27 08:51 UTC, shldhee commented on css/style.css
> +.rank_star_wrap {position: relative; top:4px; right: 10px; float: left; width: 74px; height: 12px; }
.rank_star_wrap 자식 요소인 .bg_star, .active_star 를 position: absolute 로 속성을 줘서 별점 영역 작업해서 position값이 없으면 흐트러집니다.

2017-10-27 08:52 UTC, shldhee commented on index.html
> +  <title></title>
평점&amp;리뷰 이렇게 변경하는건가요?

2017-10-27 09:00 UTC, shldhee commented on index.html
> +    <a class="content" href="#">
평점 리스트면 별표 모양인가요? 아니면 하단 설명 부분(detail_bottom)인가요?

2017-11-11 02:28 UTC, merged